### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Havoc1001** [ProjectFairnessLabs/PF-vMenu#1]
I have all of the resources in my server, i load it up....vmenu has the chameleon paint option, yet when i select an option it doesn't change on the car. I have all of the requirements in my server also.

**Comment by ribbitpoison** [comment]
Did you actually make sure to add the Chameleon Colors to your server.cfg?

**Comment by Havoc1001** [comment]
> Did you actually make sure to add the Chameleon Colors to your server.cfg?

Yes. 100% sure. The weird thing is, tx admin even shows that everything is loaded...

**Comment by ribbitpoison** [comment]
That is weird. Do you mind joining the Project Fairness Discord server and
open a ticket so we can look into this more? https://discord.gg/h32vVbEQR4

**Comment by ribbitpoison** [comment]
Closed issue due to inactivity.
