### ISSUE TITLE
time bug

### ISSUE THREAD

**Issue by ant2fx** [ProjectFairnessLabs/PF-vMenu#16]
whenever i go to change the time on client side, it flashes non stop, how can fix this its so annoying

**Comment by ribbitpoison** [comment]
Find line 111 in your permissions.cfg, and set setr vmenu_enable_time_sync from true to false.

**Comment by ant2fx** [comment]
i did and it still happened, could it be that i have another weather script?

**Comment by ribbitpoison** [comment]
try setting setr vmenu_enable_weather_sync true to false

**Comment by ant2fx** [comment]
i have both set to false, you got discord i can show you better then i can tell you

**Comment by ribbitpoison** [comment]
https://discord.gg/D7cVc8TzPN

**Comment by ribbitpoison** [comment]
Issue resolved. Closing thread.
