### ISSUE TITLE
[New Feature] Labels for Vehicle Extras

### ISSUE THREAD

**Issue by txdaniel55** [ProjectFairnessLabs/PF-vMenu#17]
As seen in this pull request for vMenu - https://github.com/TomGrobbe/vMenu/pull/275

An additional configuration file to allow for naming of vehicle extras within vMenu. I am currently running this code within normal vMenu and it functions perfectly. Would love to see this added to PF-vMenu natively.

**Comment by ribbitpoison** [comment]
@DeckardCain001 is it alright if I add this to my menu?

**Comment by DeckardCain001** [comment]
> @DeckardCain001 is it alright if I add this to the menu?
Sure - no problem. I shared the update with the community so we can all enjoy it.  Appreciate you asking! Cheers.

**Comment by ribbitpoison** [comment]
I've asked this on Discord, but can you please provide an extra.json file?

**Comment by ribbitpoison** [comment]
Closed isue, due to being complete.
