### ISSUE TITLE
Missing Weapon Tints and Addons

### ISSUE THREAD

**Issue by txdaniel55** [ProjectFairnessLabs/PF-vMenu#18]
The weapon menu is missing new tints and mods from the recent updates. For example the Bat is missing all of the new tints. The missing features can be found in this pull request from vMenu, including the recent gamebuild and missing features from previous ones. https://github.com/TomGrobbe/vMenu/pull/303

**Comment by ribbitpoison** [comment]
Fixed. Update your vMenu.
