### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by RAXIC7** [ProjectFairnessLabs/PF-vMenu#19]
I think there should be a multi-language support feature.

(INSERTED BY RIBBITPOISON)
Multi-Language support helps for brand new languages within vMenu, as the menu was mainly made in English in mind. By adding a multi-language feature, this can let people change languages of the menu so it can be easily navigated without difficulty of understanding.

**Comment by ribbitpoison** [comment]
I'll see what I can do about it. I'd need permission first before using.

**Comment by ribbitpoison** [comment]
@QuadrupleTurbo is it alright is I use this?

**Comment by QuadrupleTurbo** [comment]
> @QuadrupleTurbo is it alright is I use this?

Sure, Vespura won't merge it anyways

**Comment by ribbitpoison** [comment]
> > @QuadrupleTurbo is it alright is I use this?
> 
> Sure, Vespura won't merge it anyways

Sweet, thanks! BTW, you can join my Discord if you wish. It's in the readme.

**Comment by ribbitpoison** [comment]
Okay @QuadrupleTurbo, I'm not sure what I did.

I inserted the code as-is, and I got this on my vMenu.

![image](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/95391751/7df070fb-15f3-49fb-999c-c0e3e0e50816)

I'm not sure what I did wrong, as I followed everything correctly according to the source code.

If you mind checking [this out](https://github.com/ProjectFairnessLabs/PF-vMenu/tree/language-settings), I'd be very thankful.
