### ISSUE TITLE
Mosh_Notify - Optional

### ISSUE THREAD

**Issue by txdaniel55** [ProjectFairnessLabs/PF-vMenu#20]
Perhaps adding a config option to allow the choice of using mystic-notify or not having any notifications in regards to noclip? Have it as an option instead of a dependency.

**Comment by ribbitpoison** [comment]
The thing is, you don't need mosh_notify in order to run the menu as-is. It's optional, I forgot to disclose that.

**Comment by tristencommunity** [comment]
No idea if we're talking about the same thing here. Mythic notify or mystic notify?

**Comment by txdaniel55** [comment]
Total Brainfart on my end, I meant Mosh_Notify, as @ribbitpoison noted as being fully optional.

**Comment by tristencommunity** [comment]
Now realizing it, I pull requested this suggestion without knowing it was suggested lol

https://github.com/ProjectFairnessLabs/PF-vMenu/pull/21

**Comment by txdaniel55** [comment]
LOL. Worked out in the end.

**Comment by ribbitpoison** [comment]
we may need to have a beer after all this fellas
