### ISSUE TITLE
Location Blips setting always enabled

### ISSUE THREAD

**Issue by lkid73** [ProjectFairnessLabs/PF-vMenu#22]
In the Misc. Settings menu, the setting named "Location Blips" re-enable itself every time I reboot the vMenu. 

I tried to disabled it and saved my settings but still enabled after a reboot.

Is it possible to make it as disabled or adding a setting within the permissions.cfg to make it enabled or not. 

Thanks.

**Comment by ribbitpoison** [comment]
Location blips are hardcoded to be turned on. You can modify this on line 31, by changing `true` to `UserDefaults.MiscLocationBlips` and compiling. I'll have to update this.

**Comment by tristencommunity** [comment]
this will hopefully be fixed soon
https://github.com/ProjectFairnessLabs/PF-vMenu/pull/25
