### ISSUE TITLE
Keybind F7 doesn't work correctly for teleportation

### ISSUE THREAD

**Issue by lkid73** [ProjectFairnessLabs/PF-vMenu#23]
The keybind that we can enable in the Misc. Settings menu for easy teleporting to a waypoint, F7

It doesn't respond quite right. If I use a "regular" version of the vMenu, I got teleported right away as I pressed the keybind F7.

For some reason, I need to quickly press multiple time F7 to get teleported with the PF vMenu.

Thanks.

**Comment by ribbitpoison** [comment]
Usually, I wouldn't trust keybinds such as that. I'll check and see and reproduce the problem.
