### ISSUE TITLE
Update all menu keybinds to use RegisterKeyMapping

### ISSUE THREAD

**Issue by marshular** [ProjectFairnessLabs/PF-vMenu#24]
This also includes opening vMenu.

# EDIT 22/06/2023, INSERTED BY RIBBITPOISON:
Possible theory being that it could fix the unknown vMenu voice chat glitch that has been happening whenever you use a controller...?

**Comment by ribbitpoison** [comment]
Isn't RegisterKeyMapping only for registering commands off of only the keyboard, disabling controller support?

**Comment by marshular** [comment]
No, it enabled better controller support. Allowing for players to bind controller button to certain things that wouldn’t have been originally possible.

**Comment by ribbitpoison** [comment]
Is that so? May have to look into this.

**Comment by tristencommunity** [comment]
https://docs.fivem.net/natives/?_0xD7664FD1

**Comment by RickyB505** [comment]
Should be all done now
