### ISSUE TITLE
Personal Vehicle Options on Main Menu

### ISSUE THREAD

**Issue by ribbitpoison** [ProjectFairnessLabs/PF-vMenu#31]
As seen on other servers, their vMenu has an option on Personal Vehicle Options in the main menu. It only shows after you have a vehicle selected as your Personal Vehicle using the Personal Vehicle menu on Vehicle Related Options, or by typing /pv.

This is a minor feature, but it would be nice to add this detail.

![Image](https://user-images.githubusercontent.com/95391751/248064382-93bbdf9e-ae52-4926-afb9-2273eb9d6962.png)

**Comment by RickyB505** [comment]
done
