### ISSUE TITLE
Adding the same vehicle in both car brand category and vehicle class

### ISSUE THREAD

**Issue by KenzoHaruka** [ProjectFairnessLabs/PF-vMenu#37]
Is it possible to add it to both categories? Sometimes I feel like scrolling through multiple manufacturers instead of a single brand.

**Comment by ribbitpoison** [comment]
It's possible, as vMenu is case-sensitive. At the moment, we're currently figuring out a way to fix this problem as seen in #7.

**Comment by tristencommunity** [comment]
yeah you easily can, just have the vehicle's <vehicleMakeName> the same for all the vehicles you want to be in a category.

**Comment by tris-ten** [comment]
this should have been fixed with this [commit](https://github.com/ProjectFairnessLabs/PF-vMenu/blob/2bb99e3115ea9ebf5edbdda1b3c477222d4a8621/vMenu/menus/VehicleSpawner.cs)
