### ISSUE TITLE
Permissions for Brand Vehicles and Brand Category's

### ISSUE THREAD

**Issue by Jmanfx** [ProjectFairnessLabs/PF-vMenu#38]
Hey there,

 I was wondering if you could create a feature where you can set the permissions for who can access Brand Vehicles and/or certain Brands 
 
 An it would be great if we could set it in the permissions config like this for example: 
add_ace group.admin "vMenu.VehicleSpawner.Brands" allow

**Comment by ribbitpoison** [comment]
This brands feature is currently being worked on. You may never know if it'll work. ;)

**Comment by tristencommunity** [comment]
brand categories are created based on whatever value the `<vehicleMakeName>` is on a vehicles.meta file. meaning that each unique brand will have to have its own `"vMenu.VehicleSpawner.Brand.(brand-here)"` permission that you'll have to add to your config. and creating a system to auto-create those permissions for each brand is a little tricky atm

ill think of some ideas that could be done to allow this.

for permissions based on who can access the brands. i dont think restricting only brands should be a thing as in my eyes, its unnecessary. you either have brands enabled or disabled *(soon to be created feature)*, and have `"vMenu.VehicleSpawner.Addon"` allowed or not allowed.

**Comment by Jmanfx** [comment]
That's all good i ended up editing it myself, what i was actually trying to do was change the Brand's section to Donator Vehicles section. i did end up doing as you can see in the photo below. 


![image](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/140313828/84badc13-dde2-46f6-af3f-a84c8bb70ca1)
