### ISSUE TITLE
Makeup color bug

### ISSUE THREAD

**Issue by xCin3kk** [ProjectFairnessLabs/PF-vMenu#44]
When i creating character in vMenu and changing makeup it's works fine until i change color, but when i'm editing existing character makeup color the color of the makeup is as it is set and therefore the makeup does not look like in GTA Online, can this be fixed?

EDIT BY RIBBITPOISON: The bug can be reproduced by changing the makeup of an existing character. This also applies whenever you create a character. I am not sure why this problem occurs, but we'll have to check the older vMenu files for more info.

**Comment by ribbitpoison** [comment]
Hmm... not sure how this happened. I'll have to revise it soon as it's possible the feature may be bugged (somehow).

**Comment by xCin3kk** [comment]
maybe if it's possible add color for makeup which will be RGB color from GTA Online as the "Default" color, if this possible

**Comment by xCin3kk** [comment]
oh, okay

**Comment by ribbitpoison** [comment]
Yeah, idk. We tested the menu a few days ago after this issue was posted, and the makeup was fully working.

Your opacity is currently at 0, or you're using a non-GTA makeup that doesn't support custom colors.
