### ISSUE TITLE
Misc setting "Respawn As Default MP Character" not working anymore

### ISSUE THREAD

**Issue by Helpme0822** [ProjectFairnessLabs/PF-vMenu#51]
**Describe the bug**
The misc setting "Respawn As Default MP Character" is not working anymore. When I first spawn in or die as a different ped it doesn't put me as my Default MP Character anymore.

**To Reproduce**
1. Go to 'Misc Settings'
2. Enable 'Respawn as Default MP Character
3. Set a Default MP Character and then die as another ped or rejoin the server and you won't spawn as your default ped

**vMenu Info**:
- Server ip:
- vMenu Version (check the about menu): latest release version
- Do you have access to the files? Yes
- FXServer artifacts version: 6553

**Comment by RickyB505** [comment]
are you on a latest release or pre release whats the version code

**Comment by Helpme0822** [comment]
> are you on a latest release or pre release whats the version code

I'm using the 'PF-vMenu-v1.1.3-PR2' version

**Comment by RickyB505** [comment]
https://github.com/ProjectFairnessLabs/PF-vMenu/releases/tag/PF-v1.1.3 read the entire change log

**Comment by RickyB505** [comment]
you'll want to allow this perm to spawn as default

add_ace builtin.everyone "vMenu.PlayerAppearance.SpawnAsDefault" allow

**Comment by Helpme0822** [comment]
I did but it's also not working with that perm enabled

**Comment by RickyB505** [comment]
are you executing the permission.cfg?

**Comment by Helpme0822** [comment]
yes

**Comment by RickyB505** [comment]
not sure then

**Comment by RickyB505** [comment]
send me the permission cfg file on discord ricky3207

**Comment by Helpme0822** [comment]
done

**Comment by Helpme0822** [comment]
Ricky helped me out on discord and the solution is that the "vMenu.PlayerAppearance.SpawnAsDefault" should be on deny instead of allow

**Comment by tris-ten** [comment]
That doesn't make sense.. so you're wanting to spawn as default on the server, but if you set its PlayerAppearance.SpawnAsDefault value to false, it then works?

**Comment by tris-ten** [comment]
https://github.com/ProjectFairnessLabs/PF-vMenu/commit/b4df4aa67b935516c78d4b5bd77bf23fb09881ef

Fixed.
