### ISSUE TITLE
RegisterKeyMapping/RegisterCommand being run every tick

### ISSUE THREAD

**Issue by Rqver** [ProjectFairnessLabs/PF-vMenu#54]
Running the RegisterKeyMapping/RegisterCommand every tick will not be doing any favours at all to the performance of the resource, they only need to be ran once when the script is loaded. Would PR it but don't have access to an editor at the moment unfortunately - I imagine resmon would drop by 0.20+ by only running this once.

https://github.com/ProjectFairnessLabs/PF-vMenu/blob/c4b258650fde57bdf3563aca79618f3d04d32670/vMenu/MainMenu.cs#L506

**Comment by RickyB505** [comment]
so its not as performance killing as you might think just did the test and its maybe 0.05

**Comment by RickyB505** [comment]
![with keymapping](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/65817116/31c91979-ebcd-4e9c-b411-85de8bf24344)
![keymapping/commands removed](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/65817116/b88a3beb-7ca0-4f91-8144-1d47d36fa957)

**Comment by RickyB505** [comment]
thats with and without keymapping/commands

**Comment by RickyB505** [comment]
and tbh they were both fluctuating around the same area so its probably even less that that

**Comment by Rqver** [comment]
Oh strange I ran some tests and got a very different result, maybe I only saw it when the script first started so it was still creating all the menus etc, regardless the natives don't need to be run every tick

**Comment by RickyB505** [comment]
yeah ill fix it

**Comment by RickyB505** [comment]
https://github.com/ProjectFairnessLabs/PF-vMenu/commit/12961e7303841cb41fc9c60ad947c963a62b9ee3
