### ISSUE TITLE
MP Ped Customizations and Saved Vehicles

### ISSUE THREAD

**Issue by Mxdden01** [ProjectFairnessLabs/PF-vMenu#58]
Add an option to update your player clothing in the 'MP Ped Customizations - Saved Characters' 
Also maybe make it so that when we save a new Ped we can create categories and organises are peds same with 'Saved Vehicles'

**Comment by RickyB505** [comment]
this would be tremendously difficult

**Comment by RickyB505** [comment]
and no offence kinda unnecessary
