### ISSUE TITLE
Fix/Revamp Local Time & Weather Options

### ISSUE THREAD

**Issue by ribbitpoison** [ProjectFairnessLabs/PF-vMenu#6]
Make sure they behave like server's time and weather options, except it only works on client per user. This means, make a client-side time/weather system based on the server's version, for familiarity.

# EDIT: 22/06/2023:

As seen on other servers, their vMenu has an option on a much cleaner, more ergonomic local/client-side Time/Weather Related options. They would look like this, and would look like the server version of the Time/Weather Options, except it would only work client-side.

![Image](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/95391751/2b521af7-2526-4488-abf9-eba28ea1c784)

**Comment by ribbitpoison** [comment]
@Internal3247

"Instead of the time violently jumping when changed (client or server sided), having it change smoothly (as in, minute by minute, the same way as weather, would be much nicer. Its become an ongoing "joke" that when an admin changes the time from night to day its a 'flashbang' because of how bright it gets so quickly."

This also intends to disable the Flashbang effect whenever you swap times out, with the times transitioning similarly from GTA V Story Mode (at night/day) to Online (at day/night), respectively..

**Comment by RickyB505** [comment]
Finished
