### ISSUE TITLE
Car brands on Addon Vehicle Menu

### ISSUE THREAD

**Issue by ribbitpoison** [ProjectFairnessLabs/PF-vMenu#7]
Instead of adding the cars manually (which would be time-consuming), it scans and adds the vehicles by adding the lines using vehicleMakeName.

Instead of:

`
    "brands": [
                "Audi",
    		"Chevrolet",
    		"Nissan"
	],`

    "Audi": [
                "rs318",
    		"q820",
    		"r820"
	],
    "Chevrolet": [
                "2018zl1",
    		"ss69",
    		"camaro70"
	],
    "Nissan": [
                "nisgtr32",
    		"bnr34",
    		"17r35"
	],
`

it would be:

`  "vehicleMakeName": [
                "AUDI",
    		"CHEVROLET",
    		"NISSAN"
	],
`

All the cars would be added automatically by adding the brands. For cars that have no vehicleMakeName or hasn't been added to the list, it would be added into its own brand category called "Unknown".

**Comment by txdaniel55** [comment]
If this is implemented, it would be great if this could also apply to the default GTA V Vehicles, to have manufacturer sorting for both!

**Comment by txdaniel55** [comment]
What would be a nice feature is to keep the existing Addon Manufacturer Menu when updating to auto-sort to be used for custom categories that don't follow the vehicle make or class. 

Ex:
LSPD
Pickup Trucks
24/7 Business
Race Cars
etc.

**Comment by tristencommunity** [comment]
Actually, we won't even need the `"brands"`, we should set it up so all you have to do is put the vehicle in the `"vehicles"` table and it'll auto sort based on the vehicle's brand within each vehicles.meta. We could also make it sort based on the alphabet.

**Comment by ribbitpoison** [comment]
That would be a good idea.

**Comment by tristencommunity** [comment]
gonna start working on it :)

**Comment by tris-ten** [comment]
https://github.com/ProjectFairnessLabs/PF-vMenu/commit/2bb99e3115ea9ebf5edbdda1b3c477222d4a8621
