### ISSUE TITLE
Teleport Options Sub-Categories

### ISSUE THREAD

**Issue by ribbitpoison** [ProjectFairnessLabs/PF-vMenu#8]
While the main Teleport Options feature is complete, figuring out sub-categories has been a problem.

The idea is to add a brand new folder/sub-category for teleport locations via locations.json, similar to the old Car brands on Addon Vehicle Menu solution made a few months ago.

**Comment by tristencommunity** [comment]
I seem a bit confused on what you mean by this? Like sub-menus that players could add themselves? Like AOP locations or something?

**Comment by ribbitpoison** [comment]
Correct. Depending by category folders of teleport locations when you access the Teleport Locations menu, the submenus can vary by:

- Drift Locations
- Race Locations
- Meet Locations
- RP/AOP Locations

It would all be setup under locations.json, similar to the brands feature as seen on addons.json.

**Comment by tristencommunity** [comment]
Oh cool!

**Comment by ribbitpoison** [comment]
It would have to look like this, for example.



![Image](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/95391751/76a3ccb9-8a36-4aac-bea0-dc1189744733)

**Comment by ribbitpoison** [comment]
Thanks to a little JSON file that was provided to us indirectly, this has been reworked and added for v1.1.4.

![Image](https://github.com/ProjectFairnessLabs/PF-vMenu/assets/95391751/dcdeff6b-6871-4b00-a0bb-8e335ead6f3e)
